/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Control.CtrlPregunta;
import Control.CtrlTema;
//import DAO.temaDAO;
import DTO.Pregunta_Tema;
import DTO.Tema;
import java.util.Collection;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Daniel
 */
public class Respuestas extends javax.swing.JFrame {

    /**
     * Creates new form Respuestas
     */
    Collection<Tema> temas;
    public Respuestas() {
        initComponents();
         temas = ctrlTema.listarTemas();
        cbTemas.removeAllItems();
        Iterator it=temas.iterator();
        while(it.hasNext()){
            Tema tt = (Tema) it.next();
            cbTemas.addItem(tt.getCodigo());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbTemas = new javax.swing.JComboBox();
        btnCargar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cbPregunta = new javax.swing.JComboBox();
        cbOpcion = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPregResp = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnAgregar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Seleccione un Tema:");

        cbTemas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btnCargar.setText("Cargar");
        btnCargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCargarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Pregunta:");

        cbPregunta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbPregunta.setEnabled(false);
        cbPregunta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPreguntaActionPerformed(evt);
            }
        });

        cbOpcion.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cbOpcion.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "C", "D" }));
        cbOpcion.setEnabled(false);
        cbOpcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbOpcionActionPerformed(evt);
            }
        });

        tbPregResp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Pregunta", "Respuesta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbPregResp);

        btnAgregar.setText("Agregar Respuesta");
        btnAgregar.setEnabled(false);
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar Resuestas");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnAgregar1.setText("Volver");
        btnAgregar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar1ActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Respuesta:");

        jMenu1.setText("File");

        jMenuItem1.setText("Ingresar Respuestas al maestro");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(255, Short.MAX_VALUE)
                        .addComponent(cbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbTemas, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCargar))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnAgregar1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnGuardar))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel3))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cbTemas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCargar))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbOpcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregar)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar1)
                    .addComponent(btnGuardar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private CtrlTema ctrlTema = new CtrlTema() ;
    private CtrlPregunta ctrlPregunta = new CtrlPregunta() ;
    private void cbPreguntaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPreguntaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPreguntaActionPerformed

    private void cbOpcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbOpcionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbOpcionActionPerformed

    private void btnCargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCargarActionPerformed
        Tema t= ctrlTema.cargarTema(Integer.parseInt(cbTemas.getSelectedItem().toString()));
        actualizarTabla(t);
    }//GEN-LAST:event_btnCargarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        DefaultTableModel dft = (DefaultTableModel) tbPregResp.getModel();
        String[] datos = {cbPregunta.getSelectedItem().toString(), cbOpcion.getSelectedItem().toString()};
        dft.addRow(datos);
        tbPregResp.setModel(dft);
    }//GEN-LAST:event_btnAgregarActionPerformed
Tema temaMaestro;
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed

        cbPregunta.removeAllItems();
        temaMaestro = ctrlTema.cargarTema(0);
        Iterator it = temaMaestro.getPreguntas().iterator();
        while(it.hasNext()){
            Pregunta_Tema tt = (Pregunta_Tema) it.next();
            cbPregunta.addItem(tt.getPregunta().getCodigo());
        }
        cbPregunta.setEnabled(true);
        cbOpcion.setEnabled(true);
        btnAgregar.setEnabled(true);
        btnGuardar.setEnabled(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        DefaultTableModel dft = (DefaultTableModel) tbPregResp.getModel();
        for(int i=0; i <dft.getRowCount(); i++){
            Iterator it = temaMaestro.getPreguntas().iterator();
            while(it.hasNext()){
                Pregunta_Tema ptt = (Pregunta_Tema) it.next();
                if(ptt.getPregunta().getCodigo() == Integer.parseInt(dft.getValueAt(i, 0).toString())){
                    int rta = 0;
                    String letra =dft.getValueAt(i, 1).toString();
                    if(letra.equals("A")){
                        rta =1;
                    }else if(letra.equals("B")){
                        rta = 2;
                    }else if(letra.equals("C")){
                        rta =3;
                    }else if(letra.equals("D")){
                        rta= 4;
                    }
                    ptt.setRespuesta(rta);
                }
            }   
        }
        ctrlTema.ingresarRespuesta(temaMaestro);
        ctrlTema.desplegarRespuestas(temaMaestro);
        limpiarTabla();
        btnAgregar.setEnabled(false);
        btnGuardar.setEnabled(false);
        cbPregunta.setEnabled(false);
        cbOpcion.setEnabled(false);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar1ActionPerformed
        Examenes exa = new Examenes();
        exa.abrirPrincipal();
        this.hide();
    }//GEN-LAST:event_btnAgregar1ActionPerformed
    
    private void actualizarTabla(Tema tt){
        if(tt.getPreguntas() != null){
        DefaultTableModel dft = (DefaultTableModel) tbPregResp.getModel();
        limpiarTabla();
        Iterator it = tt.getPreguntas().iterator();
        while(it.hasNext()){
            Pregunta_Tema pt = (Pregunta_Tema) it.next();
            int rta= pt.getRespuesta();
            String letra = "";
            if(rta == 1){
                        letra = "A";
                    }else if(rta == 2){
                        letra = "B";
                    }else if(rta == 3){
                        letra = "C";
                    }else if(rta == 4){
                        letra = "D";
                    }
         
            String[] datos = {Integer.toString(pt.getNroPregunta()), letra };
            dft.addRow(datos);
        }
        tbPregResp.setModel(dft);
        }
    }
    
    public void limpiarTabla(){
        DefaultTableModel dft = (DefaultTableModel) tbPregResp.getModel();
        while(dft.getRowCount()>0) dft.removeRow(0);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Respuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Respuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Respuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Respuestas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Respuestas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAgregar1;
    private javax.swing.JButton btnCargar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JComboBox cbOpcion;
    private javax.swing.JComboBox cbPregunta;
    private javax.swing.JComboBox cbTemas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbPregResp;
    // End of variables declaration//GEN-END:variables
}
